(function(){'use strict';document.addEventListener('DOMContentLoaded',function(){initMobileNav();initThemeToggle();initTypingEffect();initNavbarScroll();initBackToTop();initScrollProgress();initRevealAnimations();initProjectFilters();initContactForm();initHoverEffects();document.querySelectorAll('.current-year').forEach(function(e){e.textContent=new Date().getFullYear()})});
function initMobileNav(){var t=document.getElementById('mobileToggle'),n=document.getElementById('mainNav');if(!t||!n)return;t.addEventListener('click',function(){n.classList.toggle('active');document.body.classList.toggle('nav-open');t.innerHTML=n.classList.contains('active')?'<i class="fas fa-times"></i>':'<i class="fas fa-bars"></i>'});document.querySelectorAll('.main-nav a').forEach(function(a){a.addEventListener('click',function(){n.classList.remove('active');document.body.classList.remove('nav-open');t.innerHTML='<i class="fas fa-bars"></i>'})})}
function initThemeToggle(){var b=document.querySelector('.theme-toggle'),c=document.querySelector('.nav-container');if(!b&&c){b=document.createElement('button');b.className='theme-toggle';b.innerHTML='<i class="fas fa-moon"></i>';c.appendChild(b)}if(!b)return;var s=localStorage.getItem('theme')||'light';document.documentElement.setAttribute('data-theme',s);updateIcon(s);b.addEventListener('click',function(){var cur=document.documentElement.getAttribute('data-theme'),nxt=cur==='dark'?'light':'dark';document.documentElement.setAttribute('data-theme',nxt);localStorage.setItem('theme',nxt);updateIcon(nxt)})}
function updateIcon(t){var i=document.querySelector('.theme-toggle i');if(i)i.className=t==='dark'?'fas fa-sun':'fas fa-moon'}
function initTypingEffect(){var e=document.querySelector('.typing-text');if(!e)return;var p=JSON.parse(e.getAttribute('data-phrases')||'["Web Developer","UI/UX Designer","Problem Solver"]'),i=0,c=0,d=false,ps=false;function tp(){var ph=p[i];if(ps){setTimeout(tp,2000);ps=false;return}e.textContent=d?ph.substring(0,c-1):ph.substring(0,c+1);d?c--:c++;if(!d&&c===ph.length){ps=true;d=true;setTimeout(tp,2000);return}if(d&&c===0){d=false;i=(i+1)%p.length}setTimeout(tp,d?50:100)}tp()}
function initNavbarScroll(){var h=document.querySelector('header');if(!h)return;var l=0;window.addEventListener('scroll',function(){var cur=window.pageYOffset;h.classList.toggle('scrolled',cur>80);h.classList.toggle('hidden',cur>l&&cur>300);l=cur},{passive:true})}
function initBackToTop(){var b=document.querySelector('.back-to-top');if(!b){b=document.createElement('button');b.className='back-to-top';b.innerHTML='<i class="fas fa-arrow-up"></i>';document.body.appendChild(b)}window.addEventListener('scroll',function(){b.classList.toggle('visible',window.pageYOffset>500)},{passive:true});b.addEventListener('click',function(){window.scrollTo({top:0,behavior:'smooth'})})}
function initScrollProgress(){var bar=document.createElement('div');bar.className='scroll-progress';document.body.appendChild(bar);window.addEventListener('scroll',function(){var h=document.documentElement.scrollHeight-window.innerHeight;bar.style.width=Math.min(window.pageYOffset/h*100,100)+'%'},{passive:true})}
function initRevealAnimations(){var els=document.querySelectorAll('.fade-in,.animate-on-scroll');if(!els.length)return;var obs=new IntersectionObserver(function(entries){entries.forEach(function(entry){if(entry.isIntersecting){entry.target.style.opacity='1';obs.unobserve(entry.target)}})},{threshold:0.1});els.forEach(function(el){obs.observe(el)})}
function initProjectFilters(){var btns=document.querySelectorAll('.filter-btn'),cards=document.querySelectorAll('.project-card');if(!btns.length)return;btns.forEach(function(btn){btn.addEventListener('click',function(){btns.forEach(function(b){b.classList.remove('active')});btn.classList.add('active');var filter=btn.getAttribute('data-filter');cards.forEach(function(card,i){if(filter==='all'||card.getAttribute('data-category')===filter){card.style.display='block';card.style.opacity='0';setTimeout(function(){card.style.opacity='1'},i*50)}else{card.style.display='none'}})})})}
function initContactForm(){var f=document.getElementById('contactForm');if(!f)return;f.addEventListener('submit',function(e){e.preventDefault();var btn=this.querySelector('button[type="submit"]'),orig=btn.textContent;btn.disabled=true;btn.innerHTML='<i class="fas fa-spinner fa-spin"></i> Sending...';setTimeout(function(){var name=document.getElementById('name')?.value||'Friend',msg=document.createElement('div');msg.className='form-success';msg.innerHTML='<i class="fas fa-check-circle"></i><h3>Thank you, '+name+'!</h3><p>Message sent. I will reply within 24 hours.</p>';f.reset();btn.parentElement.insertBefore(msg,btn);setTimeout(function(){msg.remove();btn.disabled=false;btn.textContent=orig},4000);btn.disabled=false;btn.textContent=orig},1200)})}
function initHoverEffects(){document.querySelectorAll('.social-link').forEach(function(l){l.addEventListener('mousemove',function(e){var r=l.getBoundingClientRect();l.style.transform='translate('+(e.clientX-r.left-r.width/2)*0.3+'px,'+(e.clientY-r.top-r.height/2)*0.3+'px)'});l.addEventListener('mouseleave',function(){l.style.transform=''})})}
})();
